### ISSUE TITLE
Running jqtree via npm

### ISSUE THREAD

**Issue by gadgadskiy** [mbraak/jqTree#539]
Hi!. I'm trying to use jqtree in npm area and cant understand from docs how to set up it correctly.
Current code is:
```
var http = require('http');
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const { window } = new JSDOM(`<!DOCTYPE html>`);
const $ = require('jQuery')(window);


http.createServer(function (req, res) {
     $('<div id="tree1"></div>>').appendTo('body');

    var data = [
        {
            label: "node1",
            id: 1,
            children: [{ label: "child1", id: 2 }, { label: "child2", id: 3 }]
        },
        {
            label: "node2",
            id: 4,
            children: [{ label: "child3", id: 5 }]
        }
    ];
    $("#tree1").tree({
        data: data,
        autoOpen: true,
        dragAndDrop: true
    });

     res.writeHead(200, {'Content-Type': 'text/html'});
     res.write($('body').html());
     res.end();
}).listen(8080);
```
Running this code throws error
```
TypeError: $(...).tree is not a function
    at Server.<anonymous> (D:\projects\jqtree\_examples\npmtest.js:23:17)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```
and it's logically because I didn't import 'jqtree module'.
Please help, how can I import this lib (it's already installed on PC) to run script correctly.

**Comment by mbraak** [comment]
Hello

Try this:

```
require('jqtree');
```

By the way, are you running jqtree on the server. Because that's not possible, it only runs in the browser.

Also see this code for an example using jqtree as an npm module: https://github.com/mbraak/django-mptt-admin/blob/master/frontend/django_mptt_admin.js Note that jquery is global in this example.

Greetings,
Marco

**Comment by mbraak** [comment]
closing the issue
